#! /bin/sh

xsetroot -cursor_name left_ptr
polybar top &
sxhkd &
picom -b

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/Downloads/space.png
